### ISSUE TITLE
Add support for collection member coercions

### ISSUE THREAD

**Issue by galetahub** [applift/fast_attributes#10]
Hi,

First of all thanks for a great gem!
Can you add support for collection member coercions aka:
```ruby
attribute :page_numbers, Array[Integer]
# or with custom class PhoneNumber
attribute :phone_numbers, Array[PhoneNumber]
```
Thanks

**Comment by kostyantyn** [comment]
Hey, thanks for the opened issue. We will look how to implement it. 

Also, if you like to contribute, we will highly appreciate it.

**Comment by Julzerator** [comment]
Will this be applied soon or can someone take @galetahub's work and create an add on similar to the support for UUID? https://github.com/applift/fast_attributes-uuid

**Comment by vincentdaniel** [comment]
Hi [Julzerator](/Julzerator), We will try to integrate it this week.

Fyi, this library was not actively maintained for some time which explain why this PR was never merged.
We are now committed to maintain it again 😄

**Comment by jdrzj** [comment]
Hi, @Julzerator I merged your PR. Sorry for the delay!
